### ISSUE TITLE
Breaks with inline CSS3 comment demarcation syntax.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [wtklbm/vscode-comment-highlight#1]
#### Reproduction Situations

1.	#### Single-Line

	1.	#### Example

		![Image](https://github.com/user-attachments/assets/4666dd40-6e61-49e5-843a-74677f1aa3be)

	1.	#### Reproduction

		<details>

		<blockquote>

		```CSS
		/*

			## Tasks

			1.	[ ] "Make Table Width 100% with Last Column Filling Remainder without squashing other columns content/width" [^1]
			2.	[ ] Include list indentation script. [^2]
			3.	[ ] Make `th`s truncate to the width of their accompanying `td`s. [^3]
			4.	[ ] Round the blockquote border. [^4]

			[^1]:	[?] https://stackoverflow.com/revisions/13754148/2#:~:text=table%20%7B%20width%3A%20100%25%3B%20table%2Dlayout%3A%20auto%3B%20%7D
			[^2]:	[?] https://stackoverflow.com/revisions/2730079/4#:~:text=%3C!doctype%20html%3E,%3C/html%3E
			[^3]:	[?] https://chatgpt.com/share/67717288-f908-8006-97bb-95c47201611e
			[^4]:	[?] https://stackoverflow.com/q/67900777/9731176

		*/

		:root {

			/*	## Variables */

				/*	## Font Size */

					--horizontal-font-size: 1em;
						/* If you set this to `rem`, it'll break `small` when nested inside other tags, like `q`s. However, why? */
					--vertical-font-size: 1cap;

					font-size: var(--horizontal-font-size) !important;

				/*	## Block Padding */

					--horizontal-block-padding: var(--horizontal-font-size);
					--vertical-block-padding:   var(--vertical-font-size);

					--block-padding: var(--horizontal-font-size);
						/* IDK what `--block-padding` should be set to, really. */

				/*	## Borders */

					--border-radius: 0.25rem;
					--border-color: solid color-mix(in srgb, currentColor 50%, transparent);
					--border-width: 1px;

					--border: var(--border-width) var(--border-color);

					/*
						1.	A revision of an answer to "currentColor with opacity" at Stack Overflow. [^1]

							[^1]: https://stackoverflow.com/revisions/76462953/2#:~:text=color%2Dmix(in%20srgb%2C%20currentColor%2025%25%2C%20transparent);

						2.	A comment under "How to use currentColor with rgba ?" at GitHub. [^2]

							[^2]: https://github.com/sass/sass/issues/2907#issuecomment-1531721223:~:text=This%20is%20working%20for%20me,color%2Dmix%20with%20currentColor%20are%20passing.
					*/

				--indent-size: 2em;
					tab-size: var(--indent-size) !important;
					text-indent: 0 !important;

			/*	## Properties */

				color-scheme: light dark !important;

					/* This has to be in the `:root` selector. `body` doesn't work. IDK why. */

				/*	~~~CSS
					font-family: monospace;
					~~~ */

		}

		body {

			/*	## Margins */

				/*	### Horizontal */

					margin-left:  var(--horizontal-block-padding) !important;
					margin-right: var(--horizontal-block-padding) !important;

				/*	### Vertical */

					margin-bottom: var(--vertical-block-padding) !important;
					margin-top:    var(--vertical-block-padding) !important;

			padding: 0 !important;

		}

			/*
				~~~YAML
				Type : Citation of Origin
				URI  : https://stackoverflow.com/revisions/13754148/2#:~:text=body%20%7B%20%20%20%20,%7D
				~~~
			*/

		/*	## Non-Title Text */

			:not(h1, small, sup, sub) { font-size: var(--horizontal-font-size) !important; }

				/*
					~~~YAML
					Type : Citation of Information
					URI  : https://github.com/microsoft/vscode/issues/219520#issue-2383827208:~:text=OS%20Version%20%09cpe:/o:fedoraproject:fedora:40-,Steps%20to%20Reproduce,-I've%20set%20markdown.preview.fontSize
					~~~
				*/

			hr {
				border: none !important;
				height: 1px !important;
				background-color: #000000 !important;
			}

				/*
					~~~YAML
					Type :
					URI  : https://stackoverflow.com/revisions/4151770/5#:~:text=hr%20%7B,%7D
					~~~
				*/

		/*	## Headings */

			h1, h2, h3, h4, h5, h6 {

				margin-bottom:             var(--vertical-block-padding)  !important;
				margin-top:                var(--vertical-block-padding)  !important;
				padding-bottom: calc(0.5 * var(--vertical-block-padding)) !important;

					/*
						~~~YAML
						Type : Citation of Origin
						URI  : https://stackoverflow.com/revisions/16073356/1#:~:text=h1%20%7B%20border%2Dbottom:%201px%20solid%20black%20%7D
						~~~
					*/

			}

			h1, h2, h3, h4, h5, h6, th {
				font-weight: bold !important;
				color: color-mix(in srgb, currentColor 75%, transparent) !important;
			}

			h2, h3, h4, h5, h6 {
				border-bottom: var(--border) !important;
			}

				/*	## Titles */

					h1 {
						font-size: calc(1.5 * var(--horizontal-font-size)) !important;
						margin-top:     0 !important;
						margin-bottom:  0 !important;
						padding-top:    0 !important;
						padding-bottom: 0 !important;
					}

		/*	## Indentation */

			div.block-indent {
				margin-left:   0 /* `var(--horizontal-block-padding)` */ !important;
				margin-bottom: 0 /* `var(--vertical-block-padding)`   */ !important;
			}

		/*	## Tables */

			table:not(td table):not(th table) {
				margin-left:   calc(0.125 * var(--horizontal-block-padding)) !important;
				margin-right:  calc(0.125 * var(--horizontal-block-padding)) !important;
				margin-top:                 var(--vertical-block-padding)    !important;
				margin-bottom:              var(--vertical-block-padding)    !important;
			}

			td table, th table {
				margin-left:   0 !important;
				margin-right:  0 !important;
				margin-top:    0 !important;
				margin-bottom: 0 !important;
			}

			table {
				border-collapse: collapse !important;
				width: auto !important;
			}

			table+table,
			table:is(:has(+ table)) {
				width: 100% !important;
				table-layout: auto !important;
					/* Allows content-based column sizing. */
			}

			th, td {

				border: var(--border) !important;
				padding-left:   calc(0.5  * var(--horizontal-block-padding)) !important;
				padding-right:  calc(0.5  * var(--horizontal-block-padding)) !important;
				padding-top:    calc(0.25 * var(--vertical-block-padding))   !important;
				padding-bottom: calc(0.25 * var(--vertical-block-padding))   !important;

				width: auto !important;
				overflow-wrap: break-word !important;

				text-align: inherit !important;
				vertical-align: top !important;

				/*
					~~~YAML
					Type : Citation of Origin
					URI  : https://stackoverflow.com/revisions/5671714/2#:~:text=Add%20a%20vertical%2Dalign%20property%20to,see%20examples%20at%20Mozilla's%20documentation.
					~~~
				*/

			}

			/* Ensure affected tables use auto layout. */

				table+table,
				table:is(:has(+ table)) {
					width: 100% !important;
					table-layout: auto !important;
				}

			/* Set a minimum width for `th` to ensure they don't shrink too much. */

				table+table th,
				table:is(:has(+ table)) th {
					width: auto !important;
				}

			/* Allow last `td` in affected tables to stretch without overlap. */

				table+table td:last-child,
				table:is(:has(+ table)) td:last-child {
					width: 100% !important;
				}

		/*	## Bordered */

			code:not(pre code), pre blockquote {
				border:        var(--border)        !important;
				border-radius: var(--border-radius) !important;
				background-color: color-mix(in srgb, currentColor 5%, transparent) !important;
			}

			blockquote {

				border: var(--border-width) var(--border-color) !important;

					/* This should be `1cap`, but isn't. */

				background-color: color-mix(in srgb, currentColor 5%, transparent) !important;
				border-top-right-radius:    var(--border-radius) !important;
				border-bottom-right-radius: var(--border-radius) !important;

				/* ## Margin */

					margin-top:    inherit !important;
					margin-bottom: inherit !important;
					margin-left: 0 !important; /* What does this inherit from? */
					margin-right: inherit !important;

				/* ## Padding */

					/* What does this inherit from? */

						padding-left:  calc(1 * var(--horizontal-block-padding)) !important;
						padding-right: calc(1 * var(--horizontal-block-padding)) !important;

					padding-bottom: 0                           !important;
					padding-top:    0                           !important;
					border-left:    0.375em var(--border-color) !important;

			}

		/*	## Lists */

			ol { list-style-type: decimal; }

			ol, ul {

				list-style-position: outside !important;
				padding-left: 0    !important;
				margin-left:  2rem !important;

					/*
						~~~YAML
						Type : Citation of Origin
						URI  : https://stackoverflow.com/revisions/26213863/13#:~:text=preferred%20solution%20to-,remove%20%3Cul%3E%20indentation,-is%20a%20simple
						~~~
					*/

			}

		/*	## Invisible */

			.hidden {
				visibility: collapse !important;
				display:    none     !important;
			}

					/*
						~~~YAML
						Type : Citation of Origin
						URI  : https://stackoverflow.com/revisions/45861734/1#:~:text=If%20you%20want%20to%20hide%20a%20row%20in%20a%20table%20you%20could%20just%20set%20display:%20none%20on%20it.
						~~~
					*/

		/*	## Collapsed */

			details > summary:first-of-type {
				list-style-type: none !important;
			}
			tr.child-row td {
				padding-left: var(--horizontal-block-padding) !important;
			}
				/* This needs to be changed to `em`. Probably `2rem`. */

			tr.child-row th {
				padding-left: var(--horizontal-block-padding) !important;
			}

				/*
					〃, and:

					~~~YAML
					Type : Citation of Origin
					URI:
					  - https://stackoverflow.com/questions/20687826/indenting-borders-for-table-row-tr#comment138668813_20687949:~:text=Works%20well%2C%20but%20is%20there,table%20of%20Ltr%20Latin%20text)
					  - https://stackoverflow.com/revisions/20687949/2#:~:text=since%20tr%20doesn't%20accept%20margin,jsFiddle%20to%20show%20the%20latter.
					~~~
				*/

			code {

				display: inline-block !important;

				/*	## Padding */

					/*	## Horizontal */

						padding-left:  calc(0.25 * var(--horizontal-block-padding)) !important;
						padding-right: calc(0.25 * var(--horizontal-block-padding)) !important;

					/*	## Vertical */

						padding-top:    0 !important;
						padding-bottom: 0 !important;

				/*
					## Margin

					The undermentioned `margin`s need to be reduced between `li`s with `code`s. See [this GPT-4o answer][1].

					[1]: https://stackoverflow.com/revisions/20687949/2#:~:text=since%20tr%20doesn't%20accept%20margin,jsFiddle%20to%20show%20the%20latter.
				*/

					margin-bottom: calc(0.125 * var(--vertical-block-padding)) !important;
					margin-top:    calc(0.125 * var(--vertical-block-padding)) !important;
			}

					/*
						~~~YAML
						Type : Citation of Origin
						URI  : https://stackoverflow.com/revisions/19608010/2#:~:text=%23s2%20%7B-,display:%20inline%2Dblock;,-%7D.
						~~~
					*/

		img {
			min-width : 5px !important;
			padding:    1px !important;
			border: var(--border) !important;
		}

		caption { padding-bottom: var(--vertical-block-padding) !important; }
		figure { margin: 0 !important; }
		a { text-decoration: none !important; }

		/*	## Paragraphs */

			p {
				margin-bottom: var(--vertical-block-padding) !important;
				margin-top:    var(--vertical-block-padding) !important;
			}

			td p:first-of-type { margin-top:    0 !important; }
			td p:last-of-type  { margin-bottom: 0 !important; }

		button {
			margin-top: 0.75rem /* `var(--vertical-block-padding)` */ !important;
			border:        var(--border)        !important;
			border-radius: var(--border-radius) !important;
		}

		svg {
			fill: currentColor;
		}

		sup, sub, small {
			font-size: calc(0.75 * var(--horizontal-font-size)) !important;
		}
		```

		</blockquote>

		</details>

1.	#### Multi-Line

	1.	#### Example

		![Image](https://github.com/user-attachments/assets/78e7d8e8-3574-4b4d-9a12-06fb4e9c87c0)

	1.	#### Reproduction

		<details>

		<blockquote>

		```CSS
		/*

			Tasks
			-----

			1.	[ ] "Make Table Width 100% with Last Column Filling Remainder without squashing other columns content/width" [^1]
			2.	[ ] Include list indentation script. [^2]
			3.	[ ] Make `th`s truncate to the width of their accompanying `td`s. [^3]
			4.	[ ] Round the blockquote border. [^4]

			[^1]:	https://stackoverflow.com/revisions/13754148/2#:~:text=table%20%7B%20width%3A%20100%25%3B%20table%2Dlayout%3A%20auto%3B%20%7D
			[^2]:	https://stackoverflow.com/revisions/2730079/4#:~:text=%3C!doctype%20html%3E,%3C/html%3E
			[^3]:	https://chatgpt.com/share/67717288-f908-8006-97bb-95c47201611e
			[^4]:	https://stackoverflow.com/q/67900777/9731176

		*/

		:root {

			/*	Variables
				--------- */

				/*	Font Size
					--------- */

					--horizontal-font-size: 1em;
						/* If you set this to `rem`, it'll break `small` when nested inside other tags, like `q`s. However, why? */
					--vertical-font-size: 1cap;

					font-size: var(--horizontal-font-size) !important;

				/*	Block Padding
					------------- */

					--horizontal-block-padding: var(--horizontal-font-size);
					--vertical-block-padding:   var(--vertical-font-size);

					--block-padding: var(--horizontal-font-size);
						/* IDK what `--block-padding` should be set to, really. */

				/*	Borders
					------- */

					--border-radius: 0.25rem;
					--border-color: solid color-mix(in srgb, currentColor 50%, transparent);
					--border-width: 1px;

					--border: var(--border-width) var(--border-color);

					/*	1.	A revision of an answer to "currentColor with opacity" at Stack Overflow. [^1]

							[^1]: https://stackoverflow.com/revisions/76462953/2#:~:text=color%2Dmix(in%20srgb%2C%20currentColor%2025%25%2C%20transparent);

						2.	A comment under "How to use currentColor with rgba ?" at GitHub. [^2]

							[^2]: https://github.com/sass/sass/issues/2907#issuecomment-1531721223:~:text=This%20is%20working%20for%20me,color%2Dmix%20with%20currentColor%20are%20passing. */

				--indent-size: 2em;
					tab-size: var(--indent-size) !important;
					text-indent: 0 !important;

			/*	Properties
				---------- */

				color-scheme: light dark !important;
					/* This has to be in the `:root` selector. `body` doesn't work. IDK why. */

				/*	~~~CSS
					font-family: monospace;
					~~~ */

		}

		body {

			/*	Margins
				------- */

				/*	Horizontal
					------- */

					margin-left:  var(--horizontal-block-padding) !important;
					margin-right: var(--horizontal-block-padding) !important;

				/*	Vertical
					------- */

					margin-bottom: var(--vertical-block-padding) !important;
					margin-top:    var(--vertical-block-padding) !important;

			padding: 0 !important;

		}

			/*	~~~YAML
				Type : Citation of Origin
				URI  : https://stackoverflow.com/revisions/13754148/2#:~:text=body%20%7B%20%20%20%20,%7D
				~~~ */

		/*	Non-Title Text
			-------------- */

			:not(h1, small, sup, sub) { font-size: var(--horizontal-font-size) !important; }

				/*	~~~YAML
					Type : Citation of Information
					URI  : https://github.com/microsoft/vscode/issues/219520#issue-2383827208:~:text=OS%20Version%20%09cpe:/o:fedoraproject:fedora:40-,Steps%20to%20Reproduce,-I've%20set%20markdown.preview.fontSize
					~~~ */

			hr {
				border: none !important;
				height: 1px !important;
				background-color: #000000 !important;
			}

				/*	~~~YAML
					Type :
					URI  : https://stackoverflow.com/revisions/4151770/5#:~:text=hr%20%7B,%7D
					~~~ */

		/*	Headings
			-------- */

			h1, h2, h3, h4, h5, h6 {

				margin-bottom: var(--vertical-block-padding) !important;
				margin-top: var(--vertical-block-padding) !important;
				padding-bottom: calc(0.5 * var(--vertical-block-padding)) !important;

					/*	~~~YAML
						Type : Citation of Origin
						URI  : https://stackoverflow.com/revisions/16073356/1#:~:text=h1%20%7B%20border%2Dbottom:%201px%20solid%20black%20%7D
						~~~ */

			}

			h1, h2, h3, h4, h5, h6, th {
				font-weight: bold !important;
				color: color-mix(in srgb, currentColor 75%, transparent) !important;
			}

			h2, h3, h4, h5, h6 {
				border-bottom: var(--border) !important;
			}

				/*	Titles
					------ */

					h1 {
						font-size: calc(1.5 * var(--horizontal-font-size)) !important;
						margin-top: 0 !important;
						margin-bottom: 0 !important;
						padding-top: 0 !important;
						padding-bottom: 0 !important;
					}

		/*	Indentation
			----------- */

			div.block-indent {
				margin-left: 0 /* var(--horizontal-block-padding) */ !important;
				margin-bottom: 0 /* var(--vertical-block-padding) */ !important;
			}

		/*	Tables
			------ */

			table:not(td table):not(th table) {
				margin-left: calc(0.125 * var(--horizontal-block-padding)) !important;
				margin-right: calc(0.125 * var(--horizontal-block-padding)) !important;
				margin-top: var(--vertical-block-padding) !important;
				margin-bottom: var(--vertical-block-padding) !important;
			}

			td table, th table {
				margin-left: 0 !important;
				margin-right: 0 !important;
				margin-top: 0 !important;
				margin-bottom: 0 !important;
			}

			table {
				border-collapse: collapse !important;
				width: auto !important;
			}

			table+table,
			table:is(:has(+ table)) {
				width: 100% !important;
				table-layout: auto !important;
					/* Allows content-based column sizing. */
			}

			th, td {

				border: var(--border) !important;
				padding-left: calc(0.5 * var(--horizontal-block-padding)) !important;
				padding-right: calc(0.5 * var(--horizontal-block-padding)) !important;
				padding-top: calc(0.25 * var(--vertical-block-padding)) !important;
				padding-bottom: calc(0.25 * var(--vertical-block-padding)) !important;

				width: auto !important;
				overflow-wrap: break-word !important;

				text-align: inherit !important;
				vertical-align: top !important;

				/*	~~~YAML
					Type : Citation of Origin
					URI  : https://stackoverflow.com/revisions/5671714/2#:~:text=Add%20a%20vertical%2Dalign%20property%20to,see%20examples%20at%20Mozilla's%20documentation.
					~~~ */

			}

			/* Ensure affected tables use auto layout. */

				table+table,
				table:is(:has(+ table)) {
					width: 100% !important;
					table-layout: auto !important;
				}

			/* Set a minimum width for `th` to ensure they don't shrink too much. */

				table+table th,
				table:is(:has(+ table)) th {
					width: auto !important;
				}

			/* Allow last `td` in affected tables to stretch without overlap. */

				table+table td:last-child,
				table:is(:has(+ table)) td:last-child {
					width: 100% !important;
				}

		/*	Bordered
			-------- */

			code:not(pre code), pre blockquote {
				border: var(--border) !important;
				border-radius: var(--border-radius) !important;
				background-color: color-mix(in srgb, currentColor 5%, transparent) !important;
			}

			blockquote {

				border: var(--border-width) var(--border-color) !important;
					/* This should be `1cap`, but isn't. */
				background-color: color-mix(in srgb, currentColor 5%, transparent) !important;
				border-top-right-radius: var(--border-radius) !important;
				border-bottom-right-radius: var(--border-radius) !important;

				/* Margin: */

					margin-top: inherit !important;
					margin-bottom: inherit !important;
					margin-left: 0 !important; /* What does this inherit from? */
					margin-right: inherit !important;

				/* Padding: */

					/* What does this inherit from? */
						padding-left: calc(1 * var(--horizontal-block-padding)) !important;
						padding-right: calc(1 * var(--horizontal-block-padding)) !important;

					padding-bottom: 0 !important;
					padding-top: 0 !important;
					border-left: 0.375em var(--border-color) !important;

			}

		/*	Lists
			----- */

			ol { list-style-type: decimal; }

			ol, ul {

				list-style-position: outside !important;
				padding-left: 0 !important;
				margin-left: 2rem !important;

					/*	~~~YAML
						Type : Citation of Origin
						URI  : https://stackoverflow.com/revisions/26213863/13#:~:text=preferred%20solution%20to-,remove%20%3Cul%3E%20indentation,-is%20a%20simple
						~~~ */

			}

		/*	Invisible
			--------- */

			.hidden {
				visibility: collapse !important;
				display: none !important;
			}

					/*	~~~YAML
						Type : Citation of Origin
						URI  : https://stackoverflow.com/revisions/45861734/1#:~:text=If%20you%20want%20to%20hide%20a%20row%20in%20a%20table%20you%20could%20just%20set%20display:%20none%20on%20it.
						~~~ */

		/*	Collapsed
			--------- */

			details > summary:first-of-type {
				list-style-type: none !important;
			}
			tr.child-row td {
				padding-left: var(--horizontal-block-padding) !important;
			}
				/* This needs to be changed to `em`. Probably `2rem`. */

			tr.child-row th {
				padding-left: var(--horizontal-block-padding) !important;
			}

				/*	〃, and:
					~~~YAML
					Type : Citation of Origin
					URI:
					  - https://stackoverflow.com/questions/20687826/indenting-borders-for-table-row-tr#comment138668813_20687949:~:text=Works%20well%2C%20but%20is%20there,table%20of%20Ltr%20Latin%20text)
					  - https://stackoverflow.com/revisions/20687949/2#:~:text=since%20tr%20doesn't%20accept%20margin,jsFiddle%20to%20show%20the%20latter.
					~~~ */

			code {

				display: inline-block !important;

				/*	Padding
					------- */

					/*	Horizontal
						---------- */

						padding-left:  calc(0.25 * var(--horizontal-block-padding)) !important;
						padding-right: calc(0.25 * var(--horizontal-block-padding)) !important;

					/*	Vertical
						-------- */

						padding-top:    0 !important;
						padding-bottom: 0 !important;

				/*

					Margin
					------

					The undermentioned `margin`s need to be reduced between `li`s with `code`s. See [this GPT-4o answer][1].

					[1]: https://stackoverflow.com/revisions/20687949/2#:~:text=since%20tr%20doesn't%20accept%20margin,jsFiddle%20to%20show%20the%20latter.

				*/

					margin-bottom: calc(0.125 * var(--vertical-block-padding)) !important;
					margin-top:    calc(0.125 * var(--vertical-block-padding)) !important;
			}

					/*	~~~YAML
						Type : Citation of Origin
						URI  : https://stackoverflow.com/revisions/19608010/2#:~:text=%23s2%20%7B-,display:%20inline%2Dblock;,-%7D.
						~~~ */

		img {
			min-width : 5px;
			border: var(--border) !important;
			padding: 1px !important;
		}

		caption { padding-bottom: var(--vertical-block-padding) !important; }
		figure { margin: 0 !important; }
		a { text-decoration: none !important; }

		/*	Paragraphs
			---------- */

			p {
				margin-bottom: var(--vertical-block-padding) !important;
				margin-top: var(--vertical-block-padding) !important;
			}

			td p:first-of-type { margin-top: 0 !important; }
			td p:last-of-type { margin-bottom: 0 !important; }

		button {
			margin-top: 0.75rem /* var(--vertical-block-padding) */ !important;
			border: var(--border) !important;
			border-radius: var(--border-radius) !important;
		}

		svg {
			fill: currentColor;
		}

		sup, sub, small {
			font-size: calc(0.75 * var(--horizontal-font-size)) !important;
		}
		```

		</blockquote>

		</details>

#### Environment

<table>
<tbody>
<tr>
<th>
VSC
</th>
<td>
<code>code-1.99.0-1743632525.el8.x86_64</code>
</td>
</tr>
<tr>
<th>
Extension
</th>
<td>
0.0.2
</td>
</tr>
</tbody>
</table>
